### ISSUE TITLE
about python setup.py build develop 

### ISSUE THREAD

**Issue by wu-wen-zhou** [ictnlp/BT4ST#2]
When I run the command python setup.py build develop, the following error occurs:

Traceback (most recent call last):
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3070, in _dep_map
    return self.__dep_map
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2863, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = _parse_requirement(requirement_string)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 216, in _parse_specifier
    parsed_specifiers = _parse_version_many(tokenizer)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 231, in _parse_version_many
    tokenizer.raise_syntax_error(
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/wwz/BT4ST/fairseq/setup.py", line 254, in <module>
    do_setup(package_data)
  File "/root/wwz/BT4ST/fairseq/setup.py", line 164, in do_setup
    setup(
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/command/develop.py", line 126, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 785, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2786, in requires
    dm = self._dep_map
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3072, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3082, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3135, in __init__
    super().__init__(requirement_string)
  File "/root/anaconda3/envs/bt4st/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
I did not find PyYAML in the setup.py file, how should I resolve this?

**Comment by Poeroz** [comment]
Please try to install `setuptools==59.5.0`.
